version: 1
policy:
  pullRequests: public
tasks:
  $let:
    user: ${event.sender.login}

    head_rev:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.head.sha}
      else:
        $if: 'tasks_for == "github-push"'
        then: ${event.after}
        else: ${event.release.tag_name}

    repository:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.head.repo.html_url}
      else: ${event.repository.html_url}
  in:
    $if: 'tasks_for in ["github-pull-request", "github-push"]'
    then:
      - taskId: {$eval: as_slugid("lint_task")}
        created: {$fromNow: ''}
        deadline: {$fromNow: '1 hour'}
        provisionerId: aws-provisioner-v1
        workerType: github-worker
        payload:
          maxRunTime: 3600
          image: python
          command:
            - "/bin/bash"
            - "-lcx"
            - "git clone --quiet ${repository} &&
               cd microannotate &&
               git -c advice.detachedHead=false checkout ${head_rev} &&
               pip install --quiet -r test-requirements.txt &&
               pre-commit run -a" # TODO Be smarter and run only on modified files
        metadata:
          name: microannotate lint
          description: microannotate lint
          owner: ${user}@users.noreply.github.com
          source: ${repository}/raw/${head_rev}/.taskcluster.yml

      - taskId: {$eval: as_slugid("packaging_test_task")}
        created: {$fromNow: ''}
        deadline: {$fromNow: '1 hour'}
        provisionerId: aws-provisioner-v1
        workerType: github-worker
        payload:
          maxRunTime: 3600
          image: python
          command:
            - "/bin/bash"
            - "-lcx"
            - "git clone --quiet ${repository} &&
               cd microannotate &&
               git -c advice.detachedHead=false checkout ${head_rev} &&
               python setup.py sdist &&
               pip install dist/microannotate-$(cat VERSION).tar.gz"
        metadata:
          name: microannotate packaging test
          description: microannotate packaging test
          owner: ${user}@users.noreply.github.com
          source: ${repository}/raw/${head_rev}/.taskcluster.yml
